### ISSUE TITLE
Architecture to support many models across many versions

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#29]
Single model schema -> types generation is a good start for writing functionality.

Applications will eventually require using many models across many versions. Would be interesting to evaluate go-oscal generating and providing the types for import. 

Something like generating version-explicit models and storing them in-repo for import in downstream applications. This then converts the tool to a self-supporting function of maintaining the models going foward. 

IE
`compDef := types.ComponentDefinition-1-1-1` (or some identifier)

Would also like to review the cross section of this with de-duplication. Much more complex to handle solely in the logic but still accomplishable.

**Comment by brandtkeller** [comment]
Completed in #43

**Comment by mike-winberry** [comment]
I saw this was closed, but I think it may be good to look at again at least for the types we have as part of the types folder. It could be pretty easily fixed by packaging them seperately based on their version, so right now they are all using `package oscalTypes` but if we changed that to something like `package oscal104` as part of the generation, they could be more easily imported as `compDe := oscal104.ComponentDefinition`

**Comment by brandtkeller** [comment]
@mike-winberry I think that's fair - I'd also like to remove the need of tools that consume these versioned models to need to know about them explicitly (if possible - bit of a loaded statement) - I'll open a new issue and we can refine scope.
