### ISSUE TITLE
[Generate] Break repetitive code into functions

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#44]
There are a number of repetitive blocks of code that should be broken out into single functions.

**Comment by mike-winberry** [comment]
Additional Tasks Suitable for this story:
- [ ] remove "magic" strings in favor of iterative and programatic return types
- [ ] Add comprehensive unit testing around the broken apart methods
- [ ] Create re-usable methods that leverage the information in the schema rather than hard coded values
- [ ] Create a typing map for primitive/JSON supported types that can be used to populate the struct types rather than switch case (rely on the type in the schema)
- [ ] return rather than log. (detach logic into independent pieces that can be tested and used by consumers (ie object/api) rather than one long command. (expand the test pyramid with repeatability in order to increase trust when new versions of oscal are released)
