### ISSUE TITLE
[Generate] Types/Functions for library export based on model

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#69]
Two items of focus I wanted to call out here:

1. Enhance the ability for users of the models via imports into other logic/projects based on version. Make it easy to select and important 1 -> N versions of the models easily. 

2. Create generic object creation functions such that consumers do not need to account for the complexity of versions or models. Given an OSCAL file ([]bytes?) return the applicable versioned model. We can likely break this down by model. 

CC: @mike-winberry

**Comment by brandtkeller** [comment]
Follow on to #29

**Comment by mike-winberry** [comment]
The problem with two, is that the return value will always have to be generic ie `interface{}` so anywhere it is consumed the implementor will have to be aware of the `type`(version) that is being returned in order to properly cast it and access fields, otherwise go won't know how to access any of the fields. 

The solution I can see for pipeline things is abstracting the functions against the `map[string]interface{}` that the validator implements, but that is pretty computationally inefficient as it requires a bunch of iteration and type casting, or recursion and typecasting. 

Otherwise we will likely need to version our types in a way that is coherent to consumers. And then add some logic that at least Marshalls and unmarshalls into the correct versions struct and returns as `interface{}` for them to type cast once for the version they are expecting.

**Comment by mike-winberry** [comment]
This is avoided if they just pull the type file they want from the go-oscal library and they are only worried about one version, but that adds developer maintenance and complexity that would likely lead to dead code and not having version purity with our tools, which I think would good to avoid, Im not sure how it is currently being used and wether to attempt to steer users into consistency and automation early by versioning our types explicitly.

**Comment by mike-winberry** [comment]
I think 1 and 2 are very easily implemented, I think the main set backs are going to be documentation and identifying the persona we want to target:
1. Pipeline users
  - We should abstract all use of the typing away from the pipeline users and focus on I/o compatibility so they only really need to focus on "piping" commands or finding and diagnosing problems early and in a simple consumable way. 
3. Go developers
  - I would have an expectation that go devs are at least familiar with versioned types and Golangs static typing/inflexibility of the Struct type.

**Comment by brandtkeller** [comment]
Good point - Item 1 is valuable in its own right - allowing go developers to consume explicit versions.

2 is certainly more tricky. In lula for example we may not know what the version of the `component-definition` really is until parsing (nor does lula really care at this point in time to be honest - until a change in the component-definition schema impacts `implemented-requirements`). As you noted - handing this off to go-oscal does not solve the problem as the returned `interface{}` still has to be type cast... 

Persona here (in my opinion) is go developers. I believe we'll see consumers writing functionality with go-oscal that are ultimately included in tools that a run in pipelines.

**Comment by mike-winberry** [comment]
Closing
Handled in #44
