### ISSUE TITLE
[Generate] Improve unit/ E2E tesing 

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#90]
Ways to improve the provenance of an update - particularly for a given version of OSCAL. 

Key by key comparison for schema to go types - if it's in the oscal schema it is in the types.

**Comment by mike-winberry** [comment]
blocked by: #44 
After finishing 44 and building programatic patterns that can be reused against any schema (along with the comprehensive unit tests). An "integrity" test should be created that ingests the schema, creates the structs, and then validates the structs key by key against that schema. This will likely be low perfomance and may be suitable for pipeline test rather than run with the rest of the unit test. 

This should go a long towards establishing developer and consumer trust when new versions are created. If the code patterns are broken down and well tested in the generate pkg, we should have significantly more confidence when paired by a key by key reverse validation that any new schemas that are provided are converting correctly when run against the test. (or at least we will be provided errors and a path forward to accepting the new version)
